### ISSUE TITLE
The team settings are missing in the game

### ISSUE THREAD

**Issue by Qniki** [TheLeonX/NSC-ModManager#1]
after the mod manager work, the team settings disappeared in the game, or rather, flipping through the list of characters, there are no more pre-created commands

https://github.com/TheLeonX/NSC-ModManager/assets/136499435/b6569cdc-ce3d-4e32-b598-f202d3085f29

**Comment by TheLeonX** [comment]
We cant really do anything about this, cuz of how cc2 handle pages in this game. If we want to have 9 and more pages, it has to be like that
