### ISSUE TITLE
"Mods were successfully compiled!" popup disappears, making MM unusable.

### ISSUE THREAD

**Issue by MoeruStorm** [TheLeonX/NSC-ModManager#10]
### Bug
The window displaying "Mods were successfully compiled!" sometimes does not display visually but will be opened in the background, making Mod Manager unclickable.

### Can it be reproduced?
I have not been able to consistently reproduce this bug, but it seems to happen at least somewhat often. Try repeatedly launching the game with mod manager and closing after the game begins to load the intro sequence.

### Workaround
Find the NSC-ModManager process in Task Manager, expand the tree, then force the unnamed task to close.

### What moddingapi mods do you have installed?
None.

**Comment by Sonicisthegoat** [comment]
same
