### ISSUE TITLE
New Character Select page

### ISSUE THREAD

**Issue by Vampironl** [TheLeonX/NSC-ModManager#2]
![Knipsel](https://github.com/TheLeonX/NSC-ModManager/assets/161167912/6c217d97-bdfc-425c-920f-08c2e1c56fb3)
When Adding a new Character Select page (page 8) with 1 character, the tool creates 2 slots. 1 for the character and a "ghost".

Furthermore the characters on the new page seem to be locked and can not be selected.

**Comment by TheLeonX** [comment]
Fixed

**Comment by Vampironl** [comment]
> Fixed. About ghost slot. Cant really do much a lot with it, just ignore it. It happens cuz there is less than 3 icons.

Alright!

But the characters on new pages should be selectable after the next update?

**Comment by TheLeonX** [comment]
Yes

**Comment by Vampironl** [comment]
> Yes

Perfect! Thank you! 

I'll wait for the next commit and check it out. Needless to say I will confirm the results on my end.

**Comment by Vampironl** [comment]
Confirm! All slots are selectable now, even on new pages.
