### ISSUE TITLE
Blacking out

### ISSUE THREAD

**Issue by Emmaotiki5** [TheLeonX/NSC-ModManager#3]
After I installed mooding api my game broke it is just opening at a corner and staying on black screen

**Comment by Emmaotiki5** [comment]
Please how do I clear everything the mod manager has touched I had a similar issue with your storm 4 manager it seems your programs just dont work for me what does it add to the game

**Comment by TheLeonX** [comment]
Clear game, then look for ModdingAPI in tab and press on "Delete"

**Comment by Emmaotiki5** [comment]
Did not work
