### ISSUE TITLE
Costume as Character

### ISSUE THREAD

**Issue by Vampironl** [TheLeonX/NSC-ModManager#4]
Im horribly sorry to abuse the bug tracker as a way to contact you but I didn't know any better way. 

As you might have seen I reported a bug earlyer and used your modmanager and Toolbox extensively.
I noticed when you add a costume mod for a character it doesn't matter much which page/slot you fill in the characterSelectParam file. After compiling the mod it will "reset" to the next available slot for that given character. 

I noticed however that I was able to edit the characterSelectParam after compiling and was able to move the new costume into a different slot and works like a charm. Basically saying that costumes can "look like" standalone characters.

I guess you designed your tool this way to prevent conflicts if users use different mods who assign to the same slot correct? 
However adding a new costume as a "character" is a really neat feature. 
Would it be an idea to support this funtion in the Tool? To prevent conflicts the tool can always throw a warning when you install multiple mods who assign to the same slot I would guess?
In my mind a checkbox could be added to "disable auto slot".

Once again sorry for abusing this bug tracker for more like a request then a bug. I just felt it was too neat to not suggest. 
I downloaded the repo so I will also see if I can implement this feature myself in some way but I might be too "noob" to succeed just yet :D

**Comment by TheLeonX** [comment]
> Im horribly sorry to abuse the bug tracker as a way to contact you but I didn't know any better way.
> 
> As you might have seen I reported a bug earlyer and used your modmanager and Toolbox extensively. I noticed when you add a costume mod for a character it doesn't matter much which page/slot you fill in the characterSelectParam file. After compiling the mod it will "reset" to the next available slot for that given character.
> 
> I noticed however that I was able to edit the characterSelectParam after compiling and was able to move the new costume into a different slot and works like a charm. Basically saying that costumes can "look like" standalone characters.
> 
> I guess you designed your tool this way to prevent conflicts if users use different mods who assign to the same slot correct? However adding a new costume as a "character" is a really neat feature. Would it be an idea to support this funtion in the Tool? To prevent conflicts the tool can always throw a warning when you install multiple mods who assign to the same slot I would guess? In my mind a checkbox could be added to "disable auto slot".
> 
> Once again sorry for abusing this bug tracker for more like a request then a bug. I just felt it was too neat to not suggest. I downloaded the repo so I will also see if I can implement this feature myself in some way but I might be too "noob" to succeed just yet :D

next time just use modding group for that.
i dont have any plans on implementing it, its way too hard than you think.
