### ISSUE TITLE
Something Went Wrong..

### ISSUE THREAD

**Issue by GisfaRyangga** [TheLeonX/NSC-ModManager#6]
I can't compile mods, it says something went wrong.. make sure game is close, so on. You can see from the screenshot that I attached
![Screenshot 2024-05-30 193213](https://github.com/TheLeonX/NSC-ModManager/assets/112506764/c3604c15-5586-48a7-a6a9-9ed9c2372f53)

**Comment by TheLeonX** [comment]
Try to use that version of mod manager and when you will get error, send me screenshot of it again.
[NSC-ModManager.zip](https://github.com/TheLeonX/NSC-ModManager/files/15501685/NSC-ModManager.zip)

**Comment by TheLeonX** [comment]
Try to use that version of mod manager and when you will get error, send me screenshot of it again.

**Comment by TheLeonX** [comment]
I will be able to see only one error per try, so if you still gonna get problems after fixing first issue, you will need to try to get message with other errors (if they are exist)
