### ISSUE TITLE
Shadow Clones Bug

### ISSUE THREAD

**Issue by EthanCrack1** [TheLeonX/NSC-ModManager#7]
Invisible shadow clones when you change the roster and then make a combo with Naruto or Boruto in their armor break state.

**Comment by TheLeonX** [comment]
I will fix that issue. Thanks for reporting!

**Comment by TheLeonX** [comment]
I fixed that issue. When I will upload new version (for toolbox and mod manager), it should work fine. If you have installed mods which have armor break models, notify authors of mods to remake their files cuz this issue also affected toolbox
(all that after next update)

**Comment by EthanCrack1** [comment]
Understood and noted sir, thank you very much! I think that in the future Storm Connections will be a very adaptable game in terms of mods and more accessible to everyone thanks to your tools! thx
